# Generated by Django 4.1.6 on 2023-02-10 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="first_name",),
        migrations.RemoveField(model_name="user", name="last_name",),
        migrations.AlterField(
            model_name="user",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 10, 18, 44, 59, 699234, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
