# Generated by Django 4.1.6 on 2023-02-10 19:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=20, null=True)),
                ("last_name", models.CharField(blank=True, max_length=20, null=True)),
                ("bio", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="users/profile/%Y/%m/%d/"
                    ),
                ),
            ],
            options={"verbose_name": "profile", "verbose_name_plural": "profiles",},
        ),
        migrations.AlterField(
            model_name="user",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 10, 19, 15, 20, 334672, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
