# Generated by Django 4.1.6 on 2023-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_profile_alter_user_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
