# Generated by Django 4.1.6 on 2023-02-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="carproblemlocation", name="car_type",),
    ]
